# Generated by Django 3.2.5 on 2021-09-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('no_documento', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profesional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('no_documento', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resonancia', models.ImageField(upload_to='resonancias')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.paciente')),
                ('id_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.profesional')),
            ],
        ),
    ]
