# Generated by Django 3.2.5 on 2021-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='glioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='gliomoa/')),
            ],
        ),
        migrations.CreateModel(
            name='meningioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='meningioma/')),
            ],
        ),
        migrations.CreateModel(
            name='no_tumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='no_tumor/')),
            ],
        ),
        migrations.CreateModel(
            name='pituitary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='pituitary/')),
            ],
        ),
    ]
